#sudo apt-get install git openssh-server
- hosts: all
  vars:
    username: roman
  roles:
        - desktop_environment
        - essentials
        - zsh
  
  tasks:
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    become: true
