#!/bin/bash

BRIGHT='/sys/class/backlight/intel_backlight/brightness'
MAX_BRIGHT='/sys/class/backlight/intel_backlight/max_brightness'

CURRENT=$(cat $BRIGHT)
MAX=$(cat $MAX_BRIGHT)

increase()
{
      if (($CURRENT + 300 > $MAX))
      then
	      echo $MAX > $BRIGHT
      else
	      echo $CURRENT + 300 | bc > $BRIGHT  
      fi
}

decrease()
{
      if (($CURRENT - 300 <= 0))
      then
	      echo 0 > $BRIGHT
      else
	      echo $CURRENT - 300 | bc > $BRIGHT  
      fi
}

brightness()
{
    if [[ -n $1 ]] ;then 
	case $1 in 
	"up") increase
	;;
	"down") decrease
    esac
    else
	CURRENT_PERC=$(bc -l <<< "$CURRENT/$MAX*100")
	CURRENT_PERC=$(echo $CURRENT_PERC | sed 's:\..*$::')
	echo "$CURRENT_PERC%"
    fi 
}

case $BLOCK_BUTTON in
  4) increase ;; # scroll up, increase
  5) decrease ;; # scroll down, decrease
esac

brightness $@
